name: Check Deleted Lines and Contributors

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_deleted_lines_and_contributors:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch main branch changes
        run: git fetch origin main
      
      - name: Fetch pull request changes
        run: git fetch origin pull/${{ github.event.pull_request.number }}/head:pr_branch
      
      - name: Get PR branch name
        id: pr_branch_name
        run: echo "::set-output name=branch_name::$(git rev-parse --abbrev-ref pr_branch)"
      
      - name: Diff changes
        run: git diff origin/main...$PR_BRANCH_NAME -- > diff_output.txt
      
      - name: Identify deleted lines
        run: grep '^-' diff_output.txt > deleted_lines.txt
      
      - name: Check if deleted lines were created by same contributor
        run: |
          while IFS= read -r line; do
            original_commit=$(git blame -L "/$line/" main -- "$file" | cut -d ' ' -f 1 | head -n 1)
            original_author=$(git show -s --format='%an' $original_commit)
            deleting_author=$(git show -s --format='%an' $PR_BRANCH_NAME)
            if [ "$original_author" != "$deleting_author" ]; then
              echo "Deleted line '$line' was originally created by a different contributor"
              exit 1  # Fail the workflow
            fi
          done < deleted_lines.txt
